sudo: required # 관리자 권한 갖기

language: generic # 언어 선택

services:
  - docker # 도커 환경 구성

before_install: # 스크립트를 실행할 수 있는 환경 구성
  - echo "start creating an image with dockerfile"
  - docker build -t bona/docker-react-app -f Dockerfile.dev . # 이미지 빌드

script: # 실행할 스크립트
  - docker run -e CI=true bona/docker-react-app npm run test -- --coverage

after_success: # 테스트 성공 후 일
  - echo "Test Success"